### ISSUE TITLE
Switch from PHP5.6 to PHP7

### ISSUE THREAD

**Issue by ba66e77** [usdoj/foia-api#31]
By switching to PHP7, we'll get better performance out of Drupal 8.  Update the BLT configuration so that the local VM uses PHP7 and file a support request to have our ACE environment updated to use it also.

**Comment by brockfanning** [comment]
@ba66e77 Do you think this is still in the cards? I'm looking into our local environment, and the PHP version may have an impact. If the server is going to stay at PHP5.6, I may try to "share" a local VM with another project. But if this will be moving to PHP7, then I won't go that route.

**Comment by ba66e77** [comment]
Moving to PHP7 is definitely a wise choice if for no other reason than that PHP5.6 will be EOL in just over a year.  Unless other items are re-prioritized though, I doubt that moving to PHP7 will be accomplished before our team reaches the end of our engagement.

**Comment by brockfanning** [comment]
Closing, since we just moved to PHP7.
